### ISSUE TITLE
Logo rendering incorrectly on ubuntu

### ISSUE THREAD

**Issue by mingard** [dadi/cli#15]
This is how the logo appears on ubuntu, for me at least.
<img width="231" alt="screen shot 2017-10-20 at 11 08 55" src="https://user-images.githubusercontent.com/1352469/31816227-6d5bce1a-b587-11e7-911e-0a55e3ba31d3.png">

**Comment by jimlambie** [comment]
@mingard what font do you use in the terminal?

**Comment by mingard** [comment]
@jimlambie it's a monotype. Found the issue. There's a setting in iterm for treating ambiguous spacing characters as double. It's a default in Window command prompt. I'm looking into it.

**Comment by abovebored** [comment]
I like it, very avant garde

**Comment by mingard** [comment]
So the issue is with the character code. U2593 has no fixed width, but U2591 does. This means one will render okay on all clients and the other is kind of a guess.

Here are the two:
Current (Dark shade)
```
▓▓▓▓▓  ▓▓▓▓▓▓▓
              ▓▓▓▓
     ▓▓▓▓▓▓▓    ▓▓▓▓
              ▓▓▓▓
          ▓▓▓▓▓▓▓
```
Alternative (Mid shade)
```
░░░░░  ░░░░░░░
              ░░░░
     ░░░░░░░    ░░░░
              ░░░░
          ░░░░░░░
```

**Comment by eduardoboucas** [comment]
One for @abovebored to decide.

**Comment by eduardoboucas** [comment]
When you test this, could you share a screenshot of how the logo with the new character looks in the console?

**Comment by eduardoboucas** [comment]
If this is still an issue, I suggest we move it to https://github.com/dadi/boot, where the logo is being used and pulled into various products. Closing here.
