### ISSUE TITLE
Error when installing  CDN: no such file or directory

### ISSUE THREAD

**Issue by jean-luc** [dadi/cli#36]
When installing CDN with `dadi cdn new` the following error is encountered:

```
? The target directory (/path-to-dadi/cdn) is not empty. Would you like to proceed? Yes
✔ Checking the available versions of DADI CDN
✔ Downloading boilerplate (100%)
✔ Installing DADI CDN (3.x)
fs.js:584
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open './config/config.development.json' 
```

I renamed `config.development.json.sample` to `config.development.json` and was able to start CDN but as a user the process felt interrupted and it was unclear if the installation was complete.

Ubuntu
Node: 6.13.0
NPM: 5.7.1

**Comment by eduardoboucas** [comment]
This has been fixed! 👋
